SET SERVEROUTPUT ON;

BEGIN
    DBMS_OUTPUT.PUT_LINE('Hasin');
END;
/

CREATE OR REPLACE PROCEDURE GETIDLENGTH(
    ID IN VARCHAR2
) AS
    ID_LENGTH NUMBER;
BEGIN
    SELECT
        LENGTH(ID) INTO ID_LENGTH
    FROM
        DUAL;
    DBMS_OUTPUT.PUT_LINE('Length of ID: '
                         || ID_LENGTH);
END;
/

DECLARE
    ID VARCHAR2(100);
BEGIN
    ID := &ID;
    GETIDLENGTH(ID);
END;
/