-- TASK 01 --
CREATE TABLESPACE TBS1 DATAFILE 'tbs1_data.dbf' SIZE 1M;

CREATE TABLESPACE TBS2 DATAFILE 'tbs2_data.dbf' SIZE 1M;

-- TASK 02 --
ALTER USER C_210042174 QUOTA 1M ON TBS1;

ALTER USER C_210042174 QUOTA 1M ON TBS2;

-- TASK 03 --
CREATE TABLE DEPARTMENT(
    ID INT,
    NAME VARCHAR2(32),
    CONSTRAINT DEPARTMENT_PK PRIMARY KEY(ID)
) TABLESPACE TBS1;

CREATE TABLE STUDENT(
    ID INT,
    NAME VARCHAR2(32),
    DEPT_ID INT,
    CONSTRAINT STUDENT_PK PRIMARY KEY(ID),
    CONSTRAINT STUDENT_FK FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENT(ID)
) TABLESPACE TBS1;

-- TASK 04 --
CREATE TABLE COURSE(
    COURSE_CODE VARCHAR2(32),
    NAME VARCHAR2(32),
    CREDIT NUMBER(10, 2),
    OFFERED_BY_DEPT_ID INT,
    CONSTRAINT COURSE_PK PRIMARY KEY(COURSE_CODE),
    CONSTRAINT COURSE_FK FOREIGN KEY(OFFERED_BY_DEPT_ID) REFERENCES DEPARTMENT(ID)
) TABLESPACE TBS2;

-- TASK 05 --
@"E:\DOCS\IUT\4th_Sem\cse_4410_dbms_2\Lab02\\data.sql";

-- TASK 06 --
SELECT
    C.COURSE_CODE,
    D.NAME
FROM
    COURSE     C
    FULL JOIN DEPARTMENT D
    ON C.OFFERED_BY_DEPT_ID = D.ID;

-- TASK 07 --
SELECT
    TABLESPACE_NAME,
    BYTES/1024/1024 MB
FROM
    DBA_FREE_SPACE
WHERE
    TABLESPACE_NAME='TBS1';

SELECT
    TABLESPACE_NAME,
    BYTES/1024/1024 MB
FROM
    DBA_FREE_SPACE
WHERE
    TABLESPACE_NAME='TBS2';

-- TASK 08 --
ALTER TABLESPACE TBS1 ADD DATAFILE 'tbs3_data.dbf' SIZE 1M;

-- TASK 09 --
ALTER DATABASE DATAFILE 'tbs2_data.dbf' RESIZE 15M;

-- TASK 10 --
SELECT
    TABLESPACE_NAME,
    SUM(BYTES)/1024/1024 AS "Size (MB)"
FROM
    DBA_DATA_FILES
WHERE
    TABLESPACE_NAME='TBS1'
GROUP BY
    TABLESPACE_NAME;

SELECT
    TABLESPACE_NAME,
    SUM(BYTES)/1024/1024 AS "Size (MB)"
FROM
    DBA_DATA_FILES
WHERE
    TABLESPACE_NAME='TBS2'
GROUP BY
    TABLESPACE_NAME;

-- TASK 11 --
ALTER TABLESPACE TBS1 OFFLINE;

SELECT
    TABLESPACE_NAME,
    BYTES/1024/1024 MB
FROM
    DBA_FREE_SPACE
WHERE
    TABLESPACE_NAME='TBS1';

-- TASK 12 --
DROP TABLESPACE TBS1
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

-- TASK 13 --
DROP TABLESPACE TBS2
INCLUDING CONTENTS KEEP DATAFILES
CASCADE CONSTRAINTS;